### ISSUE TITLE
你好，请问代码里KGE部分的实现和论文里是不是有些差异

### ISSUE THREAD

**Issue by songzeceng** [hwwang55/MKR#3]
我发现的差异如下：
1、根据论文2.5节，可以知道KGE部分关系向量的迭代方式是L层感知机，尾结点不变（用来计算损失）；但是代码里截然相反，尾结点是L层感知机，关系向量不变
2、根据论文里公式8，可以知道，KGE的损失函数计算的是尾结点的损失，也就是真实值t和预测值t^的损失(点乘再回归)；但代码里的真实值却经过了L层感知机的迭代。

我不明白为何会有这两个这么大的差异。另外对于训练KGE部分，我也有一定的困惑：
代码里训练KGE用了一个专门的张量rmse，看来是尾结点真实值和预测值的差值，求了平方和的均值再开方。为何要这么做，感觉既像对应论文里的公式9，又不像（代码里好像没有负采样部分）

希望作者抽空答疑解惑以下，谢谢。

**Comment by hwwang55** [comment]
你好，这里将head和tail一起用了MLP处理，主要是出于对称性的考虑。由于我们没有使用entity的feature，所以这里的真实值t其实也是一个embedding。
训练KGE时这版代码里使用的是RMSE，也可以使用其它的loss function，公式9里的score的实现方式可以有很多种。
代码里和论文里的实现细节确实有不同，给你带来的困惑我们很抱歉！
