### ISSUE TITLE
the representation of relation and tail

### ISSUE THREAD

**Issue by ProgramMonkey** [hwwang55/MKR#4]
Hi Hongwei, I am reading your code, which is very inspiring, but I am a little confused about the representation of relation and tail. In line 56, within the _build_low_layers function of the file model.py, the embedding of the tail is passed to an MLP structure, while the embedding of relation remains unchanged until concatenated with head. I believe it is contrary to the subsection 2.5 Knowledge Graph Embedding Module, where the embedding of relation should be processed with an MLP structure, and the tail should be the real feature vector. Should the embedding of the tail on line 56 be changed to the embedding of the relation?

**Comment by hwwang55** [comment]
Hi, please see the issue here: https://github.com/hwwang55/MKR/issues/3. Thanks!

**Comment by ProgramMonkey** [comment]
Thanks for your quick reply!
